### ISSUE TITLE
CDT Issue 

### ISSUE THREAD

**Issue by ManeeshaAgrawal** [AEXENT/DMIST-Issues#1]
Tried to compare All table text file of Parcesa.Got unhandled
[NAV 2009R2 std. tables all.txt](https://github.com/AEXENT/DMIST-Issues/files/5819072/NAV.2009R2.std.tables.all.txt)
[Tables.txt](https://github.com/AEXENT/DMIST-Issues/files/5819073/Tables.txt)

 exception issue.
-

**Comment by msnraju** [comment]
CDT support NAV2013R2+ versions

NAV2009 is not supported

**Comment by ManeeshaAgrawal** [comment]
Thanks! Will try with 2013 or other version
